#!/bin/bash

RET=0

run() {
    if [ $JENKINS ]; then
	"$@"
    else
	"$@" >/dev/null 2>&1
    fi
}

for i in test/alioth/*.js; do
    if run node src/rewrite.js $i; then
	echo "Successfully rewrote $i"
    else 
	RET=$?
	echo "Failed on $i!"
    fi;
done
exit $RET
